### ISSUE TITLE
The code does not coarsen the graph

### ISSUE THREAD

**Issue by ZilingLin** [GTmac/HARP#13]
I have run your code, but I found that it did not coarsening the graph. I try to find out the reason, it leads me to the sfdp, the method you use to coarsening the graph. Since I can not find any useful information from the website [GraphViz](http://www.graphviz.org), I turn to you for help.
I run the code on colab, using python2, with dateset Citeseer. I get the following message.

    Number of nodes: 3312
    Number of edges: 9072
    Underlying network embedding model: node2vec
    {'scale': -1, 'num_paths': 10, 'path_length': 80, 'sg': 1, 'sfdp_path': 'bin/sfdp_linux', 'iter_count': 1, 'sample': 0.1, 'window_size': 10, 'lr_scheme': 'default', 'representation_size': 128, 'hs': 0, 'coarsening_scheme': 2, 'alpha': 0.025, 'min_alpha': 0.001}
    Subgraph 1 with 2110 nodes and 7336 edges
    Graph Coarsening...
    Training negative sampling model...
    Start building Skip-gram + Negative Sampling model on the coarsened graphs...
    Training on graph level 0...
    Finish building Skip-gram model on the coarsened graphs.
    Subgraph 2 with 1202 nodes and 1784 edges
    Training the Negative Sampling Model...
    Finish training the Skip-gram model.

Then I check the 'tempdir' in 'read_coarsening_info' and 'external_ec_coarsening' in graph_coarsening. There were only two files there.

    ['x', 'tmp.mtx']

Looking forward to your reply.

**Comment by GTmac** [comment]
Hi Ziling,

Sorry for the late reply! Not sure what would be the problem but here are some thoughts on how you may proceed:

1) you are on linux, right? Could you try to run the sfdp program in cmd to see if it works as expected?
2) what is the exact command you used?
3) if you try some other graphs -- are they being coarsened?
