### ISSUE TITLE
How can I modify p and q in node2vec?

### ISSUE THREAD

**Issue by sunwback** [GTmac/HARP#5]
Hi.

I want to do some experiments with different p and q values, but I didn't find any way to modify p and q . 

Thank you.

**Comment by GTmac** [comment]
That's true, I did not implement the biased random walk part in node2vec. Here is a hacky solution which I used when experimenting with node2vec: first export biased random walks from node2vec, then let HARP read from these random walks. Hope this answers your question :)

**Comment by sunwback** [comment]
OK. Thanks for your answer.
