### ISSUE TITLE
IndexError: index 1719 is out of bounds for axis 0 with size 1710

### ISSUE THREAD

**Issue by RainSongg** [GTmac/HARP#6]
Hello sir,when i use a mat file with network 2159*2159 and group 2159*573,it tells me

Finish building Skip-gram model on the coarsened graphs.
Traceback (most recent call last):
  File "src/harp.py", line 77, in <module>
    sys.exit(main())
  File "src/harp.py", line 62, in main
    lr_scheme='default',alpha=0.025,min_alpha=0.001,sg=1,hs=1,coarsening_scheme=2, sample=0.5)
  File "/home/rainsong/Desktop/2/HARP-master/src/graph_coarsening.py", line 333, in skipgram_coarsening_disconnected
    embeddings[real_ind] = vec
IndexError: index 1719 is out of bounds for axis 0 with size 1710

I set the parameters by default.
Can you help me?thank you very mush.

**Comment by GTmac** [comment]
My guess is that you have some nodes without any edge in your input network -- not 100% sure

**Comment by RainSongg** [comment]
Yes,you are right,there are some nodes without any edge.
The dataset I used is about diseases and drugs,and the network is a very sparse matrix.
If I want to use your algorithm on my dataset,how can i do.
Thank you very much.

**Comment by GTmac** [comment]
One solution is to construct another graph by removing nodes without any edge, and run HARP on the new graph. You also need to preserve the mapping between node indices in the original graph versus in the new graph (note that node indices should always start from 0 and be continuous).

I can also fix this on my side, but I probably will not have time to work on this until late August. Sorry about that!

**Comment by RainSongg** [comment]
Thank  you for your help.I have solved the problem.
😀
