### ISSUE TITLE
WindowsError: [Error 2]

### ISSUE THREAD

**Issue by MarcsOne** [GTmac/HARP#7]
When I run with the example  F:\develop\Python\project\HARP>python src/harp.py --input example_graphs/citeseer/citeseer.mat --model deepwalk --output citeseer.npy --sfdp-path bin
/sfdp_linux  ， I have a problem as follows：

(python27) F:\develop\Python\project\HARP>python src/harp.py --input example_gra
phs/citeseer/citeseer.mat --model deepwalk --output citeseer.npy --sfdp-path bin
/sfdp_linux
Number of nodes: 3312
Number of edges: 9072
Underlying network embedding model: deepwalk
{'scale': -1, 'num_paths': 40, 'path_length': 10, 'sg': 1, 'sfdp_path': 'bin/sfd
p_linux', 'iter_count': 1, 'sample': 0.1, 'window_size': 10, 'lr_scheme': 'defau
lt', 'representation_size': 128, 'hs': 1, 'coarsening_scheme': 2, 'alpha': 0.025
, 'min_alpha': 0.001}
Subgraph 1 with 2110 nodes and 7336 edges
Graph Coarsening...
Traceback (most recent call last):
  File "src/harp.py", line 77, in <module>
    sys.exit(main())
  File "src/harp.py", line 62, in main
    lr_scheme='default',alpha=0.025,min_alpha=0.001,sg=1,hs=1,coarsening_scheme=
2, sample=0.1)
  File "F:\develop\Python\project\HARP\src\graph_coarsening.py", line 295, in sk
ipgram_coarsening_disconnected
    recursive_graphs, recursive_merged_nodes = external_ec_coarsening(subgraph,
sfdp_path)
  File "F:\develop\Python\project\HARP\src\graph_coarsening.py", line 221, in ex
ternal_ec_coarsening
    subprocess.call(['rm', '-r', temp_dir])
  File "F:\develop\Anaconda3\envs\python27\lib\subprocess.py", line 172, in call

    return Popen(*popenargs, **kwargs).wait()
  File "F:\develop\Anaconda3\envs\python27\lib\subprocess.py", line 394, in __in
it__
    errread, errwrite)
  File "F:\develop\Anaconda3\envs\python27\lib\subprocess.py", line 644, in _exe
cute_child
    startupinfo)
WindowsError: [Error 2]

I would be grateful if you could help me. Can you help me？

**Comment by gaochouchou** [comment]
老哥 求问你是咋整的捏，我也遇到了一样的问题。
May I ask what method you used to fix this problem, I also encountered the same problem
